### ISSUE TITLE
standalone mosca giving throw er;

### ISSUE THREAD

**Issue by prussiap** [mcollina/mosca#255]
Hi,
This is basically my first venture in anything node like and i followed your instructions for installing mosca stand alone but got this error while installing

```
       +++.+++:   ,+++    +++;   '+++    +++.
      ++.+++.++   ++.++  ++,'+  `+',++  ++,++
      +`  +,  +: .+  .+  +;  +; '+  '+  +`  +`
      +`  +.  +: ,+  `+  ++  +; '+  ;+  +   +.
      +`  +.  +: ,+  `+   +'    '+      +   +.
      +`  +.  +: ,+  `+   :+.   '+      +++++.
      +`  +.  +: ,+  `+    ++   '+      +++++.
      +`  +.  +: ,+  `+     ++  '+      +   +.
      +`  +.  +: ,+  `+  +:  +: '+  ;+  +   +.
      +`  +.  +: .+  .+  +;  +; '+  '+  +   +.
      +`  +.  +:  ++;++  ++'++   ++'+'  +   +.
      +`  +.  +:   +++    +++.   ,++'   +   +.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
```

I get the same error while running mosca on command line. 

Running OSX on latest npm, node, and os version.. not sure what else i can provide ?

**Comment by jameswomack** [comment]
It tells you the problem right there: "Error: listen EADDRINUSE"

You have another process using the same address+port.

**Comment by mcollina** [comment]
Thanks @jameswomack!
