### ISSUE TITLE
Unable to install mosca using npm in ubuntu 14.04

### ISSUE THREAD

**Issue by ashutosh-akss** [mcollina/mosca#301]
Hi, 

i just tried updating mosca but getting following error, 

i tried it with sudo permissions in both  EC2  and localhost. same issue

```
> zmq@2.11.1 install /home/ubuntu/STTarter/node_modules/mosca/node_modules/zmq
> node-gyp rebuild

make: Entering directory `/home/ubuntu/STTarter/node_modules/mosca/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
                 ^
compilation terminated.
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory `/home/ubuntu/STTarter/node_modules/mosca/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-48-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ubuntu/STTarter/node_modules/mosca/node_modules/zmq
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing zmq@2.11.1

```

**Comment by mcollina** [comment]
You should __not install node from the debian/ubuntu repositories__, as it is __completely broken__, because it cannot compile binary addons.

You should do: https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions
