### ISSUE TITLE
"Value is out of bounds" in mqtt-packet/generate.js

### ISSUE THREAD

**Issue by bmcustodio** [mcollina/mosca#304]
I'm using [mqtt-malaria](https://github.com/remakeelectric/mqtt-malaria) to stress-test a Mosca broker.  There's a publishing side sending 125000 messages (QoS1), and a subscribing side receiving and tracking those messages (QoS1 as well). As soon as the number of still-to-be-delivered messages reaches 59464 (125000 - 65536), the following error occurs and nothing else is delivered:

```json
{
    "name":"mosca",
    "hostname":"mosca-dev-n1",
    "pid":5565,
    "client":"beem.listr-4513",
    "level":40,
    "err":{
        "message":"value is out of bounds",
        "name":"TypeError",
        "stack":"(see below)"
    },
    "msg":"value is out of bounds",
    "time":"2015-07-16T11:40:50.206Z",
    "v":0
}
```

```
TypeError: value is out of bounds
    at checkInt (buffer.js:716:11)
    at Buffer.writeUInt8 (buffer.js:760:5)
    at writeNumber (/var/lib/mosca/mosca/node_modules/mosca/node_modules/mqtt-connection/node_modules/mqtt-packet/generate.js:568:10)
    at publish (/var/lib/mosca/mosca/node_modules/mosca/node_modules/mqtt-connection/node_modules/mqtt-packet/generate.js:257:12)
    at generate (/var/lib/mosca/mosca/node_modules/mosca/node_modules/mqtt-connection/node_modules/mqtt-packet/generate.js:15:14)
    at DestroyableTransform.process [as _transform] (/var/lib/mosca/mosca/node_modules/mosca/node_modules/mqtt-connection/lib/generateStream.js:13:16)
    at DestroyableTransform.Transform._read (/var/lib/mosca/mosca/node_modules/mosca/node_modules/mqtt-connection/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/var/lib/mosca/mosca/node_modules/mosca/node_modules/mqtt-connection/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/var/lib/mosca/mosca/node_modules/mosca/node_modules/mqtt-connection/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/var/lib/mosca/mosca/node_modules/mosca/node_modules/mqtt-connection/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
```

**Comment by mcollina** [comment]
It's a bug: https://github.com/mcollina/mosca/blob/master/lib/client.js#L215. I will deliver a fix asap.

**Comment by bmcustodio** [comment]
@mcollina is there any workaround one can use while you work on it?

**Comment by mcollina** [comment]
It's a 2 lines fixes (reset the `nextId` property to 0 when it its the limit), you can do it yourself and send a PR.

**Comment by psorowka** [comment]
I am curious about the implications of that finding. Wouldn't anybody who used QoS1 seriously stumble over that?

**Comment by mcollina** [comment]
Probably not, I didn't. MQTT is a protocol for sending very few messages,
mostly from the device to the cloud. And every now and then a connection
drops, and that counter gets restarted.
Il giorno gio 16 lug 2015 alle 22:16 Peter Sorowka <notifications@github.com>
ha scritto:

**Comment by psorowka** [comment]
Interesting view.. I have several applications where clients send continuously about 5 msgs per sec and run without reconnect for a few hours. That would exceed the 65K limit after about 3.5 hours. I never had problems with Mosca on that because such applications use QoS0....

**Comment by mcollina** [comment]
Anyway @bmcustodio what are the results?
