### ISSUE TITLE
iojs v3 compatibility

### ISSUE THREAD

**Issue by psorowka** [mcollina/mosca#338]
I am trying to update mosca so that the tests pass on iojs v3 but have a hard time with it.

What I have done so far is basically just updating dependencies, my current status can be found here: https://github.com/skybus-io/mosca/tree/feature/iojsv3

The only problem I face is related to the _maxInflightMessages-Test_ on websockets. It works without problems about 3 out of 10 times. The other times it produces fun errors like

```
1) mosca.Server - Websocket should disconnect a client if it has more thant 1024 inflight messages:
     Uncaught TypeError: Cannot assign to read only property 'target' of invalid compressed data
      at WebSocket.onError (/app/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:422:18)
      at emitTwo (events.js:87:13)
      at WebSocket.emit (events.js:172:7)
      at Receiver.onerror (/app/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:832:10)
      at Receiver.error (/app/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:317:8)
      at /app/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:528:32
      at /app/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:354:9
      at InflateRaw.onError (/app/node_modules/websocket-stream/node_modules/ws/lib/PerMessageDeflate.js:222:5)
      at emitOne (events.js:77:13)
      at InflateRaw.emit (events.js:169:7)
      at Zlib._handle.onerror (zlib.js:366:10)
```

or

```
 1) mosca.Server - Websocket should have the max inflight message limit configurable:
     Uncaught TypeError: Cannot assign to read only property 'target' of continuation frame cannot follow current opcode
      at WebSocket.onError (/app/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:422:18)
      at emitTwo (events.js:87:13)
      at WebSocket.emit (events.js:172:7)
      at Receiver.onerror (/app/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:832:10)
      at Receiver.error (/app/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:317:8)
      at Receiver.processPacket (/app/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:208:12)
      at Receiver.add (/app/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:91:24)
      at Socket.firstHandler (/app/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:774:22)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:521:20)
```

The finally raised error is obviously a problem of the `ws` package, which I have already described here: https://github.com/websockets/ws/issues/553

However, the root error seems to come from that zlib line and be caused by a race condition between the test case emitting more messages while the socket is already closed. I don't understand why this behavior is introduced by iojs:v3, though. It seems to work without problems in node:0.10, node:0.12, iojs:v1, iojs:v2.

Another issue might be - please correct me if I am wrong - that this test case does not differentiate between a correctly closed connection (as expected), or an error that happened due to request overflow or similar.

I have digged for a couple of hours now and am resignating for now. No idea what is going on here.

**Comment by psorowka** [comment]
Okay, I am still in conversation with the guys from the `ws` package, which obviously handles the error in a wrong way. 

However, when I fix `ws` locally, I get the error `done() called multiple times` because it seems that 

```
  function buildClient(done, callback) {
    var client = createConnection(settings.port, settings.host);

    client.once('error', done);
    client.stream.once('close', function() {
      setImmediate(done);
    });

    client.on("connected", function() {
      callback(client);
    });
  }
```
(https://github.com/mcollina/mosca/blob/master/test/abstract_server.js#L36-L39)

fires both callbacks. However, I still don't get if that is just an issue of the test case or with the websockets implementation in mosca or the websockets package, because I don't see why this behavior is introduced in iojs 3.

@mcollina as you have for sure more insights because you have done the websockets implementation, do you have a clue where the problem might be?

**Comment by sahilsk** [comment]
@psorowka for me all tests are passing.

I clone your repository(iojsv3) , made nvm to use iojsv3.2.0 and executed tests

```
$ iojs -v                                                                                                                   system
v3.2.0
$ node --version                                                                                                            system
v3.2.0
$ nvm current                                                                                                               system
iojs-v3.2.0
```

To install dependencies
```
$ npm test
...
    ✓ should disconnect a client if it has more thant 1024 inflight messages (368ms)
    ✓ should disconnect a client if it has more thant 1024 inflight messages (1141ms)
    ✓ should disconnect a client if it has more thant 1024 inflight messages (683ms)
    ✓ should disconnect a client if it has more thant 1024 inflight messages (388ms)
    ✓ should disconnect a client if it has more thant 1024 inflight messages (1034ms)
    ✓ should disconnect a client if it has more thant 1024 inflight messages (859ms)
...
   on closed
      ✓ should remove the clientConnected event from the server
      ✓ should remove the clientDisconnected event from the server
      ✓ should remove the published event from the server
    memory
      ✓ should publish rss every minute
      ✓ should publish heapTotal every minute
      ✓ should publish heapUsed every minute

  932 passing (50s)
```

Please let me know if i am missing something or Can you help me reproduce it?

**Comment by sahilsk** [comment]
@psorowka for me all tests are passing.

I clone your repository(iojsv3) , made nvm to use iojsv3.2.0 and executed tests

```
$ iojs -v                                                                                                                   system
v3.2.0
$ node --version                                                                                                            system
v3.2.0
$ nvm current                                                                                                               system
iojs-v3.2.0
```

To install dependencies
```
$ npm test
...
    ✓ should disconnect a client if it has more thant 1024 inflight messages (368ms)
    ✓ should disconnect a client if it has more thant 1024 inflight messages (1141ms)
    ✓ should disconnect a client if it has more thant 1024 inflight messages (683ms)
    ✓ should disconnect a client if it has more thant 1024 inflight messages (388ms)
    ✓ should disconnect a client if it has more thant 1024 inflight messages (1034ms)
    ✓ should disconnect a client if it has more thant 1024 inflight messages (859ms)
...
   on closed
      ✓ should remove the clientConnected event from the server
      ✓ should remove the clientDisconnected event from the server
      ✓ should remove the published event from the server
    memory
      ✓ should publish rss every minute
      ✓ should publish heapTotal every minute
      ✓ should publish heapUsed every minute

  932 passing (50s)
```

Please let me know if i am missing something or Can you help me reproduce it?

**Comment by psorowka** [comment]
thanks for your effort!

I can confirm that all tests pass on iojs 3.2.0. The described behavior is reproducible on iojs 3.1.0, which was the latest version when I faced the problems. 

Very cool, I can close this.

**Comment by mcollina** [comment]
Folks, can you send a PR? :)
Also, can you update `websocket-stream` to 2.0.2? Thanks!

**Comment by psorowka** [comment]
be patient :) currently running final tests on travis. PR will come very soon

**Comment by mcollina** [comment]
No worries, I saw this closed, so that's why I asked! :)
