### ISSUE TITLE
Authentication & Authorization

### ISSUE THREAD

**Issue by SebDominguez** [mcollina/mosca#357]
I have followed [this guide](https://github.com/mcollina/mosca/wiki/Authentication-&-Authorization#using-moscas-standalone-authorizer-with-an-embedded-mosca). However, by adding the `credentials` setting to my `moscaSettings` I receive the following error message:

``` sh
$ node app.js -v | bunyan
/Users/Sebastien/node_modules/mosca/lib/server.js:105
    callback(new Error(errMessage));
    ^
TypeError: undefined is not a function
    at EventEmitter.Server (/Users/Sebastien/node_modules/mosca/lib/server.js:105:5)
    at Object.<anonymous> (/Users/Sebastien/matteo/app.js:36:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

[code](https://gist.github.com/SebDominguez/9de9a843a08ad93bdbe3) 

In order to fix this error I have changed the `credentials` setting to `credentialsWhatever` and I've also changed the `loadAuthorizer` `program.credentials` to `program.credentialsWhatever`.
Without that fix / correction, the `loadAuthorizer` was accepting all the connection.

I assume that the fix that I use is a sloppy way to fix these errors. Is there a better or proper way to fix these errors ?

**Comment by mcollina** [comment]
Possibly there is a fix to be done in https://github.com/mcollina/mosca/blob/master/lib/options.js

**Comment by ivory9334** [comment]
i have the same issue here. i can't use tls credentials and user authentification credentials. i have to rename the credential option to add both options

**Comment by geoffroysaunier** [comment]
where can i make a change in the credentials to fix this problem ?
i have the same issue than @SebDominguez and i use barely the same solution.

**Comment by SebDominguez** [comment]
up ? :)

**Comment by mcollina** [comment]
I'll have a look when I'll have a look :). Sorry about being rude, but I'm short on time these days, and I prefer spending my OSS time building the new major version of Mosca.

Feel free either to chip in or to submit a PR in the meanwhile.

**Comment by mcollina** [comment]
Is this still an issue? Feel free to reopen.

**Comment by kiralikbeyin** [comment]
@mcollina You have to update your sample code, its not working.

https://github.com/mcollina/mosca/wiki/Authentication-&-Authorization
