### ISSUE TITLE
Redis host problem

### ISSUE THREAD

**Issue by Chimit** [mcollina/mosca#375]
Hello!
I try to use [Redis example](https://github.com/mcollina/mosca/wiki/Mosca-basic-usage#in-this-example-we-will-be-using-redis), but get some errors. My Redis server is launched from Vagrant (Laravel's Homestead) and has IP 192.168.10.10.

So in my JS-file I changed the host value:
```
var ascoltatore = {
  type: 'redis',
  redis: require('redis'),
  db: 12,
  port: 6379,
  return_buffers: true, // to handle binary payloads
  host: "192.168.10.10"
};
```

But when I try to launch this script I get:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at RedisClient.on_error (/Users/user/Code/mosca/node_modules/mosca/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/Users/user/Code/mosca/node_modules/mosca/node_modules/redis/index.js:106:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
```

If I'm not mistaken, the host IP hadn't been changed from 127.0.0.1 to 192.168.10.10.

**Comment by PritamUpadhyay** [comment]
May be this can help...

https://github.com/mcollina/mosca/blob/master/examples/Server_Wtih_All%20Interfaces-Settings.js

**Comment by mcollina** [comment]
Is this still an issue? Please reopen if that's the case.
