### ISSUE TITLE
Mosca on Heroku

### ISSUE THREAD

**Issue by ccravens** [mcollina/mosca#392]
After a lot of trial and error, I am successfully able to embed mosca into my Node app and deploy to Heroku. Below is a sample of how I do this:

```javascript
var express = require('express');
var http = require('http');
var mosca = require('mosca');

var app = express();
var server = http.createServer(app);

var pubsubsettings = {
	type: 'mongo',
	url: process.env.MONGOLAB_URI ||  || 'mongodb://localhost:27017/app',
	pubsubCollection: 'mqtt',
	mongo: {}
};

var server = new mosca.Server({
	backend: pubsubsettings,
	persistence: {
		factory: mosca.persistence.Mongo,
		url: process.env.MONGOLAB_URI || 'mongodb://localhost:27017/app'
	}
}, function() {
	server.attachHttpServer(app);
});

server.on('ready', function() {
	console.log('Mosca is running');
});
```

And our client code looks like:
```javascript
var client = mqtt.connect('mqtt://app.herokuapp.com:80');
client.on('connect', function(){
    console.log('client connected');
    client.subscribe('chat');
    console.log('suscribed to chat')
});

client.on('message', function(topic, message){
      console.log('message received');
});

client.publish('chat', JSON.stringify(m));
```

When I'm developing and testing locally, everything works great, clients subscribe, I can publish, and all clients subscribed to that channel are receiving messages.

However, with the exact same codebase I deploy to Heroku. Mosca starts properly, I can see clients connect and disconnect, and I can even see messages that are published to a topic in the Heroku logs. The problem is, clients that are subscribed to that topic do not receive the message. Everything works locally, we have even tested through ngrok just to make sure we could do it through the Internet. However, when deploying to Heroku it does not work.

I will also note that we tried connecting to test.mosca.io with the same results. Our clients reported that they connected appropriately, but no messages are being received by clients subscribed to the same topic.

Any ideas as to why this works locally or through ngrok but once we push to Heroku messages are not being received by the clients?

Thanks!!

**Comment by mcollina** [comment]
You need to connect with:

```js
var client = mqtt.connect('ws://app.herokuapp.com:80');
client.on('connect', function(){
    console.log('client connected');
    client.subscribe('chat');
    console.log('suscribed to chat')
});

client.on('message', function(topic, message){
      console.log('message received');
});

client.publish('chat', JSON.stringify(m));
```

Because Heroku only supports WebSocket, not plain tcp.

**Comment by ccravens** [comment]
Hello and thank you for your quick response.

the mqtt:// protocol gets switched to ws:// by the library. However, we have tried the following protocols with no success: 1) mqtt://app.herokuapp.com 2) ws://app.herokuapp.com:80 3) wss://app.herokuapp.com:443

Like I stated, both clients are connecting to the Mosca service, and the Mosca service is receiving the message (I can see the message output in the heroku logs like the following):

```bash
2016-01-15T15:29:22.124925+00:00 app[web.1]: client connected mqttjs_3098c1ad
2016-01-15T15:29:22.195497+00:00 app[web.1]: subscribed :  chat/56980eb7bb0d4d0a00ec3040
2016-01-15T15:29:22.131169+00:00 app[web.1]: Published $SYS/VkqhAeGOe/new/clients :  mqttjs_3098c1ad
2016-01-15T15:29:22.205964+00:00 app[web.1]: Published $SYS/VkqhAeGOe/new/subscribes :  {"clientId":"mqttjs_3098c1ad","topic":"chat/56980eb7bb0d4d0a00ec3040"}
2016-01-15T15:29:31.942329+00:00 app[web.1]: client connected mqttjs_10f1ce13
2016-01-15T15:29:32.019355+00:00 app[web.1]: subscribed :  chat/56980eb7bb0d4d0a00ec3040
2016-01-15T15:29:31.945400+00:00 app[web.1]: Published $SYS/VkqhAeGOe/new/clients :  mqttjs_10f1ce13
2016-01-15T15:29:32.024595+00:00 app[web.1]: Published $SYS/VkqhAeGOe/new/subscribes :  {"clientId":"mqttjs_10f1ce13","topic":"chat/56980eb7bb0d4d0a00ec3040"}
2016-01-15T15:29:39.823961+00:00 app[web.1]: Published chat/56980eb7bb0d4d0a00ec3040 :  <Buffer 7b 22 6d 65 73 73 61 67 65 22 3a 22 63 68 61 74 20 74 65 73 74 22 2c 22 75 73 65 72 49 64 22 3a 22 35 36 39 38 30 65 38 32 62 62 30 64 34 64 30 61 30 ... >
2016-01-15T15:29:52.373745+00:00 app[web.1]: Published chat/56980eb7bb0d4d0a00ec3040 :  <Buffer 7b 22 6d 65 73 73 61 67 65 22 3a 22 74 65 73 74 32 22 2c 22 75 73 65 72 49 64 22 3a 22 35 36 39 38 30 65 38 36 62 62 30 64 34 64 30 61 30 30 65 63 33 ... >
2016-01-15T15:29:59.024291+00:00 app[web.1]: unsubscribed :  chat/5697bb12fcea8432046f0f8a
2016-01-15T15:29:59.123546+00:00 app[web.1]: Published $SYS/VkqhAeGOe/new/unsubscribes :  {"clientId":"mqttjs_19eff4fd","topic":"chat/5697bb12fcea8432046f0f8a"}
2016-01-15T15:29:59.025301+00:00 app[web.1]: clientDisconnected :  mqttjs_19eff4fd
2016-01-15T15:29:59.151919+00:00 app[web.1]: Published $SYS/VkqhAeGOe/disconnect/clients :  mqttjs_19eff4fd
```

However, no one is receiving the messages that are published. I'm at a loss for why, because everything works perfect locally but then when deploying the exact same codebase to Heroku, clients do not receive messages. Is there any sort of logging I can do to try and debug why this is the case?

Thanks!

**Comment by mcollina** [comment]
I fear it might be a mongodb issue. Try deploying without that configured, and let's see.

**Comment by ccravens** [comment]
Hey @mcollina:

we switched to an in memory persistence and now verified that it does work. The following is our working config settings for the Mosca server:

```javascript
	var server = new mosca.Server({
		persistence: {
			factory: mosca.persistence.Memory
		}
	}, function() {
		server.attachHttpServer(app);
	});
```

What are suggestions for a persistence of MQTT messages? Is this an issue that needs to be opened and looked at? Something we can help contribute to? Thanks!

**Comment by mcollina** [comment]
The problem is with MongoLab more than with Heroku itself. Which version of Mongo are they running?

**Comment by ccravens** [comment]
I see this when logging into the MongoLab: mongod version: 3.0.7

**Comment by mcollina** [comment]
Than that's https://github.com/mcollina/mosca/issues/337

**Comment by ccravens** [comment]
It looks like the PR was merged into ascoltatori back in September 3... has this updated ascoltatori been merged into mosca? I have just checked my package.json and am at the latest release Mosca 0.32.1 which was released 2015-09-21T06:50:04.503Z

**Comment by ccravens** [comment]
I just looked in the ascaltatori package at the following location:
```bash
node_modules/mosca/node_modules/ascoltatori/lib/mongo_ascoltatore.js:195
```
And saw:
```javascript
that.db.db(that._pubsubCollection).stats({}, function (err, stats) {
```
Which according to the PR should be:
```javascript
that.db.db(that.db.databaseName).stats({}, function (err, stats) {
```

**Comment by mcollina** [comment]
Not sure, I have to check all those and wrap up a release of Ascoltatori and Mosca.

**Comment by kiralikbeyin** [comment]
@ccravens 

Please can you share your packages.json

I am having problem with zmq. Do you have any suggestion?

```
remote: -----> Building dependencies
remote:        Prebuild detected (node_modules already exists)
remote:        Rebuilding any native modules
remote:        
remote:        > zmq@2.15.3 install /tmp/build_c31aca4bfe065cc3321a5228a400a9a9/node_modules/zmq
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory `/tmp/build_c31aca4bfe065cc3321a5228a400a9a9/node_modules/zmq/build'
remote:        CXX(target) Release/obj.target/zmq/binding.o
remote:        ../binding.cc:28:17: fatal error: zmq.h: No such file or directory
remote:        #include <zmq.h>
remote:        ^
remote:        compilation terminated.
remote:        make: *** [Release/obj.target/zmq/binding.o] Error 1
remote:        make: Leaving directory `/tmp/build_c31aca4bfe065cc3321a5228a400a9a9/node_modules/zmq/build'
remote:        gyp ERR! build error
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_c31aca4bfe065cc3321a5228a400a9a9/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
remote:        gyp ERR! stack     at emitTwo (events.js:106:13)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
remote:        gyp ERR! System Linux 3.13.0-91-generic
remote:        gyp ERR! command "/tmp/build_c31aca4bfe065cc3321a5228a400a9a9/.heroku/node/bin/node" "/tmp/build_c31aca4bfe065cc3321a5228a400a9a9/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_c31aca4bfe065cc3321a5228a400a9a9/node_modules/zmq
remote:        gyp ERR! node -v v6.2.2
remote:        gyp ERR! node-gyp -v v3.3.1
remote:        gyp ERR! not ok
remote:        
remote:        npm ERR! Linux 3.13.0-91-generic
remote:        npm ERR! argv "/tmp/build_c31aca4bfe065cc3321a5228a400a9a9/.heroku/node/bin/node" "/tmp/build_c31aca4bfe065cc3321a5228a400a9a9/.heroku/node/bin/npm" "rebuild"
remote:        npm ERR! node v6.2.2
remote:        npm ERR! npm  v3.9.5
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
remote:        npm ERR! Make sure you have the latest version of node.js and nam installed.
remote:        npm ERR! If you do, this is most likely a problem with the zmq package,
remote:        npm ERR! not with nam itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-gyp rebuild
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs zmq
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls zmq
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_c31aca4bfe065cc3321a5228a400a9a9/npm-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        Some possible problems:
remote:        
remote:        - node_modules checked into source control
remote:        https://blog.heroku.com/node-habits-2016#9-only-git-the-important-bits
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote: 
remote:  !     Push rejected, failed to compile Node.js app

```


```
{
  "name": "zxcasd",
  "version": "1.0.0",
   "main": "index.js",
  "dependencies": {
    "body-parser": "^1.15.2",
    "express": "^4.13.4",
    "fs": "^0.0.2",
    "http": "^0.0.0",
    "json-query": "^2.1.0",
    "mosca": "^2.0.1",
    "node-gyp": "^3.4.0",
    "path": "^0.12.7",
    "pkg-config": "^1.1.1",
    "zmq": "^2.15.3"
  },
  "engines": {
    "node": "6.2.2"
  },
  "devDependencies": {},
  "scripts": {
    "start": "node index.js"
  }
}
```

**Comment by kiralikbeyin** [comment]
Forget heroku i deployed mosca and mongo with digital ocean very easly 10$ free credit here --> https://m.do.co/c/38b1c11ea6ea they send an email if you add a payment method, write DROPLET10 to promo code. Totally 20 $ means 4 months :)

First install once click deploy node.js 

2-Follow this https://www.digitalocean.com/community/tutorials/how-to-set-up-automatic-deployment-with-git-with-a-vps

3-Install mongo https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

No headache happy developer :)

**Comment by felangga** [comment]
I've commented the mongodb stuff and trying to run this on my heroku server but it won't connect. 
Already replaced mqtt:// to ws://
Anything wrong ?

**Comment by javiermelendezc** [comment]
Is there a way to avoid the use of ws:// in mosca?
Eg. If an embedded device is not able to establish connections to ws:// but works good on mqtt:// and http:// on local development?
Or is this a problem with the cloud provider and how they handle connections? What's the configuration that has to be managed in order to work under this restriction?
