### ISSUE TITLE
mosca -v error

### ISSUE THREAD

**Issue by marvic42** [mcollina/mosca#416]
Hello,

installed mosca using "npm install mosca".
After installation, checked mosca -v,  following  error flashed

odroid@odroid:~$ mosca -v
       +++.+++:   ,+++    +++;   '+++    +++. 
      ++.+++.++   ++.++  ++,'+  `+',++  ++,++ 
      +`  +,  +: .+  .+  +;  +; '+  '+  +`  +` 
      +`  +.  +: ,+  `+  ++  +; '+  ;+  +   +. 
      +`  +.  +: ,+  `+   +'    '+      +   +. 
      +`  +.  +: ,+  `+   :+.   '+      +++++. 
      +`  +.  +: ,+  `+    ++   '+      +++++. 
      +`  +.  +: ,+  `+     ++  '+      +   +. 
      +`  +.  +: ,+  `+  +:  +: '+  ;+  +   +. 
      +`  +.  +: .+  .+  +;  +; '+  '+  +   +. 
      +`  +.  +:  ++;++  ++'++   ++'+'  +   +. 
      +`  +.  +:   +++    +++.   ,++'   +   +. 

module.js:340
    throw err;
    ^
Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/mosca/lib/persistence/memory.js:29:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

How to solve this.

Answers Appreciated

**Comment by mcollina** [comment]
Which versions of node/npm are you using? Something went wrong in your installation of Mosca.

**Comment by marvic42** [comment]
Node v0.10.24 npm 3.7.2
Yes flashed some errors. How did it completed with errors.
