### ISSUE TITLE
websocket error: "not opened"

### ISSUE THREAD

**Issue by mepdr** [mcollina/mosca#433]
Hi, today I got the following error:

```
{"name":"mosca","hostname":"server","pid":4888,"client":"mqttjs_1211c063","level":40,` "err":{"message":"not opened","name":"Error","stack":"Error: not opened   
at WebSocket.send (C:\\Users\\operatore\\node_modules\\mosca\\node_modules\\ws\\lib\\WebSocket.js:217:38) 
at DestroyableTransform.socketWriteNode [as _transform] (C:\\Users\\operatore\\node_modules\\mosca\\node_modules\\websocket-stream\\stream.js:38:12) 
at DestroyableTransform.Transform._read (C:\\Users\\operatore\\node_modules\\mosca\\node_modules\\readable-stream\\lib\\_stream_transform.js:184:10)
at DestroyableTransform.Transform._write (C:\\Users\\operatore\\node_modules\\mosca\\node_modules\\readable-stream\\lib\\_stream_transform.js:172:12)
at doWrite (C:\\Users\\operatore\\node_modules\\mosca\\node_modules\\readable-stream\\lib\\_stream_writable.js:237:10)
at writeOrBuffer (C:\\Users\\operatore\\node_modules\\mosca\\node_modules\\readable-stream\\lib\\_stream_writable.js:227:5)
at DestroyableTransform.Writable.write (C:\\Users\\operatore\\node_modules\\mosca\\node_modules\\readable-stream\\lib\\_stream_writable.js:194:11)
at write (C:\\Users\\operatore\\node_modules\\mqtt-connection\\node_modules\\readable-stream\\lib\\_stream_readable.js:623:24)
at flow (C:\\Users\\operatore\\node_modules\\mqtt-connection\\node_modules\\readable-stream\\lib\\_stream_readable.js:632:7)
at DestroyableTransform.pipeOnReadable (C:\\Users\\operatore\\node_modules\\mqtt-connection\\node_modules\\readable-stream\\lib\\_stream_readable.js:664:5)"},"msg":"not opened","time":"2016-03-14T22:46:29.089Z","v":0}
```

**Comment by mcollina** [comment]
Is this happening all the time, or just randomly?

**Comment by mepdr** [comment]
Randomly, I haven't found a way to reproduce it yet

**Comment by mcollina** [comment]
This is actually normal: the websocket gets closed early (the user loses wifi reception, close chrome..) and the connection dies with an error.

**Comment by mepdr** [comment]
in this case isn't better to silent it?

**Comment by mcollina** [comment]
Not really, it is worth knowing some of your connections are dropping.
