### ISSUE TITLE
mosca trying to use local redis

### ISSUE THREAD

**Issue by G3z** [mcollina/mosca#434]
I took your redis example and connected it to a docker redis image
```javascript
var ascoltatore = {
  type: 'redis',
  redis: require('redis'),
  db: 0,
  port: 32768,
  return_buffers: true, // to handle binary payloads
  host: "192.168.99.100"
};
```

```
> node index.js

  ascoltatori:redis connecting to 192.168.99.100:32768 +0ms
  ascoltatori:redis selected database 0 +5ms
  ascoltatori:redis connecting to 192.168.99.100:32768 +1ms
  ascoltatori:redis selected database 0 +1ms
  ascoltatori:redis created sub connection +6ms
  ascoltatori:redis created pub connection +1ms
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1065:14)
```

I don't get who is trying to connect to a local redis... do you have any idea ?

**Comment by G3z** [comment]
i put a couple of `console.log` in `lib/persistance/redis` 

```javascript
RedisPersistence.prototype._buildClient = function() {
  var options = this.options;
  console.log(options);
  console.log(options.redisOptions);
  var client = redis.createClient(
    options.port || 6379,
    options.host || "127.0.0.1",
    options.redisOptions);

  if (options.db) {
    client.select(options.db);
  }

  if (options.password) {
    client.auth(options.password);
  }

  return client;
};
```

this is console output now
```
> node index.js

{ channel: '$SYS/moscaSync',
  ttl: { subscriptions: 3600000, packets: 3600000 },
  storeMessagesQos0: false,
  factory:
   { [Function: RedisPersistence]
     super_: { [Function: AbstractPersistence] super_: [Object] } } }
undefined
{ channel: '$SYS/moscaSync',
  ttl: { subscriptions: 3600000, packets: 3600000 },
  storeMessagesQos0: false,
  factory:
   { [Function: RedisPersistence]
     super_: { [Function: AbstractPersistence] super_: [Object] } } }
undefined
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1065:14)
```

**Comment by G3z** [comment]
i did not configure persistence host && port :(
```javascript
var ascoltatore = {
  type: 'redis',
  redis: require('redis'),
  db: 0,
  port: 32768,
  return_buffers: true, // to handle binary payloads
  host: "192.168.99.100"
};

var moscaSettings = {
  port: 1883,
  backend: ascoltatore,
  persistence: {
    factory: mosca.persistence.Redis,
    port: 32768,
    host: "192.168.99.100"
  }
};
```
