### ISSUE TITLE
mosco mqtt broker server fails on creating

### ISSUE THREAD

**Issue by dzilbers** [mcollina/mosca#440]
It looks like missing dependency?
node v5.10.0

my server.js:
var mosca = require('mosca')
 
var pubsubsettings = {
  type: 'mongo',
  url: 'mongodb://localhost:27017/mqtt',
  pubsubCollection: 'myCollections',
  mongo: {}
};
 
var settings = {
  port: 1883,
  persistence: mosca.persistence.Memory,
  backend: pubsubsettings
};
 
//here we start mosca
var server = new mosca.Server(settings);

The error:
C:\Dani-R&D\JS\mqttd\node_modules\mosca\lib\server.js:109
      throw new Error(errMessage);
      ^

Error: is not of a type(s) object
    at EventEmitter.Server (C:\Dani-R&D\JS\mqttd\node_modules\mosca\lib\server.js:109:13)
    at Object.<anonymous> (C:\Dani-R&D\JS\mqttd\server.js:17:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

**Comment by mcollina** [comment]
This is it. The error is not one of the best :/.

```js
var mosca = require('.')

var pubsubsettings = {
  type: 'mongo',
  url: 'mongodb://localhost:27017/mqtt',
  pubsubCollection: 'myCollections',
  mongo: {}
};

var settings = {
  port: 1883,
  persistence: {
    factory: mosca.persistence.Memory
  },
  backend: pubsubsettings
};

//here we start mosca
var server = new mosca.Server(settings);
```
