### ISSUE TITLE
MQTT server crashed with "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by Urmik** [mcollina/mosca#442]
Hello,

I am using mosca amqp.
I am doing benchmark testing to check concurrent connections.
My client side code is:

***************************************************************************************************************************
var mqtt = require('mqtt');
var host = 'mqtt://IP:Port';
var myVar = setInterval(function ()
            {
                myTimer()
            }, 500);

function myTimer() {
    if (i == 30000) {
        clearInterval(myVar);
    }
    else {
       
        var options = {
            clientId: UniqueId(),
        };
        var client = mqtt.connect(host, options);
        client.on('connect', function () {
            client.subscribe(UniqueId(), { qos: 0 });
        });
    }
}

function myStopFunction() {
    clearInterval(myVar);
}

****************************************************************************************************************************
After 4K to 5K connections, my node mqtt server crashed and I am getting following error

*****************************************************************************************************************************
events.js:141
      throw er; // Unhandled 'error' event
      ^

RangeError: Maximum call stack size exceeded
    at exports.Promise.emitSuccess (D:\TOOLS\Nodejs\node_modules\amqp\lib\promise.js:49:13)
    at Queue.Channel._handleTaskReply (D:\TOOLS\Nodejs\node_modules\amqp\lib\channel.js:69:20)
    at Queue._onMethod (D:\TOOLS\Nodejs\node_modules\amqp\lib\queue.js:384:29)
    at Queue.Channel._onChannelMethod (D:\TOOLS\Nodejs\node_modules\amqp\lib\channel.js:85:12)
    at Connection._onMethod (D:\TOOLS\Nodejs\node_modules\amqp\lib\connection.js:443:28)
    at AMQPParser.self.parser.onMethod (D:\TOOLS\Nodejs\node_modules\amqp\lib\connection.js:136:12)
    at AMQPParser._parseMethodFrame (D:\TOOLS\Nodejs\node_modules\amqp\lib\parser.js:363:10)
    at frameEnd (D:\TOOLS\Nodejs\node_modules\amqp\lib\parser.js:93:16)
    at frame (D:\TOOLS\Nodejs\node_modules\amqp\lib\parser.js:78:14)
    at header (D:\TOOLS\Nodejs\node_modules\amqp\lib\parser.js:64:14)

******************************************************************************************************************************

I have tried with setting "--stack-size" , but it didn't work.

Regards,
Urmik

**Comment by mcollina** [comment]
No idea really. Can you try to reproduce it just by using amqp?

**Comment by Urmik** [comment]
Hello,

Thanks for you reply.
In other test, I am not passing amqp in mosca backend setting. And started my client again.
Then also ,server has been stopped accepting any new connection after 4k-5k connections without any error.
So It might not be amqp issue.
Is there any setting I have missed? Please help me in it.

Regards,
Urmik

**Comment by mcollina** [comment]
It is possibly a problem with the number of sockets available on your box. Check your host network settings (ulimit, etc...).

**Comment by Urmik** [comment]
Thanks,

I did following setting on my box

**********************************************************************************************************************
In sysctl.conf

net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_mem = 50576   64768   98152
net.core.netdev_max_backlog = 2500
net.ipv4.ip_local_port_range = 1024 65535
fs.file-max = 1000000
fs.nr_open = 1000000   
net.netfilter.nf_conntrack_max = 1048576
net.core.somaxconn = 1024


in limits.confg

 root            soft    nofile          1000000
 root            hard    nofile          1000000
 *                 soft    nofile          1000000
 *                 hard    nofile          1000000
 root            soft    stack           unlimited
 root            hard    stack           unlimited
 *               soft    stack           unlimited
 *               hard    stack           unlimited

**********************************************************************************************************************

I have tested with my client script quite a few time to check concurrent connections.But each time MQTT server has been stopped receiving any new connection after 28k-30k connections.

**Comment by mcollina** [comment]
It depends on the amount of memory, CPU and configuration of your hosts.
Closing.

**Comment by AdamMagaluk** [comment]
Seeing the same thing as well, will try to reproduce with only amqp and file an issue on their repo.

```
Server: RangeError: Maximum call stack size exceeded
    at min (native)
    at Buffer.subarray (native)
    at Buffer.slice (buffer.js:617:23)
    at allocate (buffer.js:88:23)
    at new Buffer (buffer.js:53:12)
    at parseFields (/root/mqtt-load-test/basic-broker/node_modules/amqp/lib/parser.js:315:17)
    at AMQPParser._parseMethodFrame (/root/mqtt-load-test/basic-broker/node_modules/amqp/lib/parser.js:359:14)
    at frameEnd (/root/mqtt-load-test/basic-broker/node_modules/amqp/lib/parser.js:93:16)
    at frame (/root/mqtt-load-test/basic-broker/node_modules/amqp/lib/parser.js:78:14)
    at header (/root/mqtt-load-test/basic-broker/node_modules/amqp/lib/parser.js:64:14)
```

**Comment by mcollina** [comment]
Thanks!

**Comment by AdamMagaluk** [comment]
Here's the issue i filed on amqp repo https://github.com/postwait/node-amqp/issues/429
