### ISSUE TITLE
Mosca server crashing every hour

### ISSUE THREAD

**Issue by jchang333** [mcollina/mosca#468]
We are running Mosca v1.3 in docker container on Mesos using redis as broker and persistent storage.  The service keep crashing every hour and brought back by Mesosphere.

/usr/src/app/mosca/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /usr/src/app/mosca/node_modules/async/lib/async.js:43:36
    at /usr/src/app/mosca/node_modules/async/lib/async.js:723:17
    at /usr/src/app/mosca/node_modules/async/lib/async.js:167:37
    at /usr/src/app/mosca/lib/persistence/redis.js:161:11
    at /usr/src/app/mosca/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/usr/src/app/mosca/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/usr/src/app/mosca/node_modules/async/lib/async.js:209:22)
    at Command.callback (/usr/src/app/mosca/lib/persistence/redis.js:157:13)
    at normal_reply (/usr/src/app/mosca/node_modules/redis/index.js:662:21)
    at RedisClient.return_reply (/usr/src/app/mosca/node_modules/redis/index.js:722:9)

**Comment by mcollina** [comment]
Confirmed that it can throw, but not sure why it happens every hour. Would you like to send a fix?
It should be simple, basically set `callback` to `null` after calling it once in https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L161.
I think this is happening because of reconnection of the Redis socket.

**Comment by mcollina** [comment]
Please try v2.0.0, feel free to reopen if still a bug.
