### ISSUE TITLE
Problem on running mosca - Error Unexpected identifier: qlobber.js:227

### ISSUE THREAD

**Issue by ricardoff5** [mcollina/mosca#512]
Im having problem on running mosca at ubuntu.

When i run:

`mosca -v | bunyan`

 ```
+++.+++:   ,+++    +++;   '+++    +++.
      ++.+++.++   ++.++  ++,'+  `+',++  ++,++
      +`  +,  +: .+  .+  +;  +; '+  '+  +`  +`
      +`  +.  +: ,+  `+  ++  +; '+  ;+  +   +.
      +`  +.  +: ,+  `+   +'    '+      +   +.
      +`  +.  +: ,+  `+   :+.   '+      +++++.
      +`  +.  +: ,+  `+    ++   '+      +++++.
      +`  +.  +: ,+  `+     ++  '+      +   +.
      +`  +.  +: ,+  `+  +:  +: '+  ;+  +   +.
      +`  +.  +: .+  .+  +;  +; '+  '+  +   +.
      +`  +.  +:  ++;++  ++'++   ++'+'  +   +.
      +`  +.  +:   +++    +++.   ,++'   +   +.

/usr/local/lib/node_modules/mosca/node_modules/qlobber/lib/qlobber.js:227
    for (w of st.keys())
           ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/mosca/node_modules/qlobber/index.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

How can i fix?

I tried to update node to last one stable, doesnt work:

`sudo n 0.10.36`
`sudo n stable`

Thanks

**Comment by mcollina** [comment]
Mosca v2 does not support node v0.10. You need to install mosca v1.

**Comment by ricardoff5** [comment]
Which node is required?

**Comment by mcollina** [comment]
0.12+

**Comment by mcollina** [comment]
4 is recommended.
