### ISSUE TITLE
Mosco app not running on Heroku

### ISSUE THREAD

**Issue by hashans** [mcollina/mosca#522]
Hi,

I wanted to host Mosco on Heroku. But it's cause an error. It's successfully running on local. Here's the log i extracted from Heroku. 

`> mqqt-broker@0.0.1 start /app
> node server.js
/app/node_modules/mosca/lib/server.js:109
 Error: is not of a type(s) integer
      throw new Error(errMessage);
   at Module.load (module.js:458:32)
    at Module._compile (module.js:541:32)
    at EventEmitter.Server (/app/node_modules/mosca/lib/server.js:109:13)
    at Object.<anonymous> (/app/server.js:21:14)
    at Object.Module._extensions..js (module.js:550:10)
    at run (bootstrap_node.js:352:7)
    at Module.runMain (module.js:575:10)
     at startup (bootstrap_node.js:144:9)
 at Function.Module._load (module.js:409:3)
     at tryModuleLoad (module.js:417:12)     at bootstrap_node.js:467:3`

My node and npm versions are as follows.
Node -v : 6.3.0
npm -v : 3.10.3

**Comment by hashans** [comment]
Resolved the issue by converting the PORT environment variable to an integer
