### ISSUE TITLE
Mosca Crashing Server

### ISSUE THREAD

**Issue by ccravens** [mcollina/mosca#525]
It appears that having the Mosca library included in the server may be crashing it. At, what appears to be random intervals, we get the following:

```javascript
/Users/ccravens/Business/company/Clients/project/src/project-core/node_modules/ascoltatori/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

Error: Cannot stat if collection is capped or not
    at /Users/ccravens/Business/company/Clients/project/src/project-core/node_modules/ascoltatori/lib/mongo_ascoltatore.js:235:26
    at handleCallback (/Users/ccravens/Business/company/Clients/project/src/project-core/node_modules/ascoltatori/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/ccravens/Business/company/Clients/project/src/project-core/node_modules/ascoltatori/node_modules/mongodb/lib/collection.js:1503:20
```

**Comment by ccravens** [comment]
Actually this might be due to the connection to the database being poor. Might not be an ascoltatori issue at all... Just wanted to verify everyone's thoughts before closing it.

**Comment by mcollina** [comment]
I think it's a combination of both. The connection is poor, _and_ ascoltatori is failing too early: https://github.com/mcollina/ascoltatori/blob/master/lib/mongo_ascoltatore.js#L232-L237.

I think we should add a retry mechanism there.

**Comment by soszrg** [comment]
I have the similar issue. When it appears, I find that the amount of connections with mongodb is more than the biggest number. But, if I use node v0.12 and mosca1.0, the server is well.

**Comment by soszrg** [comment]
the error message if the following:
TypeError: Cannot call method 'indexOf' of undefined
    at new Server (/var/moscaserver/node_modules/mongodb/lib/server.js:86:11)
    at Object.<anonymous> (/opt/elaas/dev/mqtt/mqtt_server.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by dushyantbangal** [comment]
@mcollina has there been any fix for this? can you suggest a workaround?
My MQTT just stops working after this error :(

**Comment by mcollina** [comment]
No I have not worked on a fix. Would you like to send a PR?

**Comment by dushyantbangal** [comment]
I've come up with the following (dirty) retry logic:

```
if (err) 
{
    if(!retryCount)
        retryCount=0;
    if(retryCount<3)
    {
        debug('checkCappedAndPoll -> Cannot stat isCapped. Retry');
        
        setTimeout(function(){
            that._checkCappedAndPoll(latest, ++retryCount);
        },500)
            
        return;
    }else{
        debug('checkCappedAndPoll -> Cannot stat isCapped. Give up');

        that.emit('error', new Error('Cannot stat if collection is capped or not'));
        that._handlingCursorFailure = false;
        return;
    }
}
```
Should I be putting the `setTimeout` of 500ms or directly retrying?

**Comment by mcollina** [comment]
@dushyantbangal does that solves your problem?

I think we can increase the maximum retry count to 5 and do something like `setTimeout(func, 100 * retryCount)`, so that it increase overtime (and the first one is 0).

**Comment by dushyantbangal** [comment]
I'm not really able to recreate the issue, it happens sometimes.
But I did try the following:
1. Set `error=true` for count 0,1,2
2. Execute the broker with `DEBUG=ascoltatori:mongodb`

For counts 0,1,2 the execution went in retry, and after count 2 the polls were successful.

**Comment by mcollina** [comment]
Can you send a PR then?

**Comment by dushyantbangal** [comment]
Sure, will do!
