### ISSUE TITLE
Mosca takes ages to install on alpine linux

### ISSUE THREAD

**Issue by nite** [mcollina/mosca#584]
Not sure if this is the right place for this - but mosca takes over 5 mins to npm install on alpine linux - seemingly as no binaries for zmq, kerberos, leveldb, snappy etc - an excerpt from the logs below.

```
npm WARN deprecated mongodb@2.1.21: Please use 2.2.16 or higher due to a regression in updateOne/Many upsertedId return value
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
...
> kerberos@0.0.22 install /usr/local/lib/node_modules/mosca/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/usr/local/lib/node_modules/mosca/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:36:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:37:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function 'authenticate_gss_client_wrap':
../lib/kerberosgss.c:446:19: warning: variable 'server_conf_flags' set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:1236:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory '/usr/local/lib/node_modules/mosca/node_modules/kerberos/build'

> fs-ext@0.5.0 install /usr/local/lib/node_modules/mosca/node_modules/fs-ext
> node-gyp configure build

make: Entering directory '/usr/local/lib/node_modules/mosca/node_modules/fs-ext/build'
  CXX(target) Release/obj.target/fs-ext/fs-ext.o
../fs-ext.cc: In function 'void EIO_After(uv_work_t*)':
../fs-ext.cc:108:20: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     argv[0] = Nan::NanErrnoException(store_data->error);
                    ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:108:20: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     argv[0] = Nan::NanErrnoException(store_data->error);
                    ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:108:55: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     argv[0] = Nan::NanErrnoException(store_data->error);
                                                       ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE Flock(Nan::NAN_METHOD_ARGS_TYPE)':
../fs-ext.cc:297:45: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (i != 0) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                             ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:297:45: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (i != 0) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                             ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:297:68: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (i != 0) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                                    ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE Seek(Nan::NAN_METHOD_ARGS_TYPE)':
../fs-ext.cc:339:56: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (offs_result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                        ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:339:56: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (offs_result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                        ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:339:79: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (offs_result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                                               ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE Fcntl(Nan::NAN_METHOD_ARGS_TYPE)':
../fs-ext.cc:375:51: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                   ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:375:51: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                   ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:375:74: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                                          ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE UTime(Nan::NAN_METHOD_ARGS_TYPE)':
../fs-ext.cc:433:47: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "utime", "", *path));
                                               ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:433:47: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "utime", "", *path));
                                               ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:433:90: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "utime", "", *path));
                                                                                          ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE StatVFS(Nan::NAN_METHOD_ARGS_TYPE)':
../fs-ext.cc:469:47: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "statvfs", "", *path));
                                               ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:469:47: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "statvfs", "", *path));
                                               ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
../fs-ext.cc:469:92: warning: 'v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)' is deprecated [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "statvfs", "", *path));
                                                                                            ^
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:862:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> NanErrnoException(
                                              ^
  SOLINK_MODULE(target) Release/obj.target/fs-ext.node
  COPY Release/fs-ext.node
make: Leaving directory '/usr/local/lib/node_modules/mosca/node_modules/fs-ext/build'

> snappy@5.0.5 install /usr/local/lib/node_modules/mosca/node_modules/snappy
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/mosca/node_modules/snappy/build'
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/usr/local/lib/node_modules/mosca/node_modules/snappy/build'

> zmq@2.15.3 install /usr/local/lib/node_modules/mosca/node_modules/zmq
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/mosca/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
compilation terminated.
zmq.target.mk:92: recipe for target 'Release/obj.target/zmq/binding.o' failed
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/mosca/node_modules/zmq/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.39-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mosca/node_modules/zmq
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> leveldown@1.4.6 install /usr/local/lib/node_modules/mosca/node_modules/leveldown
> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v7.2.1 arch=arm platform=linux)
make: Entering directory '/usr/local/lib/node_modules/mosca/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/leveldb_main.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.18.0/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
../src/batch.cc: In static member function 'static v8::Local<v8::Value> leveldown::Batch::NewInstance(v8::Local<v8::Object>, v8::Local<v8::Object>)':
../src/batch.cc:71:69: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     instance = constructorHandle->GetFunction()->NewInstance(1, argv);
                                                                     ^
In file included from /root/.node-gyp/7.2.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/7.2.1/include/node/node.h:42,
                 from ../src/batch.cc:1:
/root/.node-gyp/7.2.1/include/node/v8.h:3288:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/7.2.1/include/node/v8config.h:329:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/batch.cc:74:69: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     instance = constructorHandle->GetFunction()->NewInstance(2, argv);
                                                                     ^
In file included from /root/.node-gyp/7.2.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/7.2.1/include/node/node.h:42,
                 from ../src/batch.cc:1:
/root/.node-gyp/7.2.1/include/node/v8.h:3288:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/7.2.1/include/node/v8config.h:329:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
  CXX(target) Release/obj.target/leveldown/src/batch_async.o
  CXX(target) Release/obj.target/leveldown/src/database.o
../src/database.cc: In static member function 'static v8::Local<v8::Value> leveldown::Database::NewInstance(v8::Local<v8::String>&)':
../src/database.cc:166:67: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   instance = constructorHandle->GetFunction()->NewInstance(1, argv);
                                                                   ^
In file included from /root/.node-gyp/7.2.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/7.2.1/include/node/node.h:42,
                 from ../src/database.cc:6:
/root/.node-gyp/7.2.1/include/node/v8.h:3288:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/7.2.1/include/node/v8config.h:329:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/database.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE leveldown::Database::Iterator(Nan::NAN_METHOD_ARGS_TYPE)':
../src/database.cc:458:16: warning: 'v8::TryCatch::TryCatch()' is deprecated: Use isolate version [-Wdeprecated-declarations]
   v8::TryCatch try_catch;
                ^
In file included from /root/.node-gyp/7.2.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/7.2.1/include/node/node.h:42,
                 from ../src/database.cc:6:
/root/.node-gyp/7.2.1/include/node/v8.h:7015:40: note: declared here
   V8_DEPRECATED("Use isolate version", TryCatch());
                                        ^
/root/.node-gyp/7.2.1/include/node/v8config.h:329:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
  CXX(target) Release/obj.target/leveldown/src/database_async.o
  CXX(target) Release/obj.target/leveldown/src/iterator.o
../src/iterator.cc: In static member function 'static v8::Local<v8::Object> leveldown::Iterator::NewInstance(v8::Local<v8::Object>, v8::Local<v8::Number>, v8::Local<v8::Object>)':
../src/iterator.cc:331:69: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     instance = constructorHandle->GetFunction()->NewInstance(2, argv);
                                                                     ^
In file included from /root/.node-gyp/7.2.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/7.2.1/include/node/node.h:42,
                 from ../src/iterator.cc:6:
/root/.node-gyp/7.2.1/include/node/v8.h:3288:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/7.2.1/include/node/v8config.h:329:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/iterator.cc:334:69: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     instance = constructorHandle->GetFunction()->NewInstance(3, argv);
                                                                     ^
In file included from /root/.node-gyp/7.2.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/7.2.1/include/node/node.h:42,
                 from ../src/iterator.cc:6:
/root/.node-gyp/7.2.1/include/node/v8.h:3288:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/root/.node-gyp/7.2.1/include/node/v8config.h:329:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
  CXX(target) Release/obj.target/leveldown/src/iterator_async.o
  CXX(target) Release/obj.target/leveldown/src/leveldown.o
```

**Comment by mcollina** [comment]
You are using ARM on a probably "slow" CPU for embedded applications.

The current architecture of Mosca is monolithic, and there is not much you can do. However, you can use https://github.com/mcollina/aedes, which is smaller and has all the features as separate modules.
