### ISSUE TITLE
Invalid qos vector error

### ISSUE THREAD

**Issue by marqueeeeeee** [mcollina/mosca#617]
`{"pid":8616,"hostname":"IPGMKTHBV1","name":"mosca","level":40,"time":14889390745
50,"msg":"Invalid qos vector","type":"Error","stack":"Error: Invalid qos vector\
n    at suback (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\mqtt-packet\\
generate.js:400:11)\n    at generate (C:\\Velocity\\Installed\\Mosca MQTT\\node_
modules\\mqtt-packet\\generate.js:25:14)\n    at DestroyableTransform.process [a
s _transform] (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\mqtt-connectio
n\\lib\\generateStream.js:13:16)\n    at DestroyableTransform.Transform._read (C
:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\mqtt-connection\\node_modules\
\readable-stream\\lib\\_stream_transform.js:184:10)\n    at DestroyableTransform
.Transform._write (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\mqtt-conne
ction\\node_modules\\readable-stream\\lib\\_stream_transform.js:172:12)\n    at
doWrite (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\mqtt-connection\\nod
e_modules\\readable-stream\\lib\\_stream_writable.js:237:10)\n    at writeOrBuff
er (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\mqtt-connection\\node_mod
ules\\readable-stream\\lib\\_stream_writable.js:227:5)\n    at DestroyableTransf
orm.Writable.write (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\mqtt-conn
ection\\node_modules\\readable-stream\\lib\\_stream_writable.js:194:11)\n    at
Connection.callWrite3Args [as _callWrite] (C:\\Velocity\\Installed\\Mosca MQTT\\
node_modules\\reduplexer\\index.js:50:25)\n    at Connection.write [as _write] (
C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\reduplexer\\index.js:147:17)\
n    at doWrite (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\reduplexer\\
node_modules\\readable-stream\\lib\\_stream_writable.js:237:10)\n    at writeOrB
uffer (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\reduplexer\\node_modul
es\\readable-stream\\lib\\_stream_writable.js:227:5)\n    at Connection.Writable
.write (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\reduplexer\\node_modu
les\\readable-stream\\lib\\_stream_writable.js:194:11)\n    at Connection.(anony
mous function) [as suback] (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\m
qtt-connection\\connection.js:64:12)\n    at Client.<anonymous> (C:\\Velocity\\I
nstalled\\Mosca MQTT\\node_modules\\mosca\\lib\\client.js:510:23)\n    at Result
sHolder.release (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\fastparallel
\\parallel.js:183:12)\n    at parallel (C:\\Velocity\\Installed\\Mosca MQTT\\nod
e_modules\\fastparallel\\parallel.js:39:16)\n    at Object.map (C:\\Velocity\\In
stalled\\Mosca MQTT\\node_modules\\steed\\steed.js:57:5)\n    at Client.handleSu
bscribe (C:\\Velocity\\Installed\\Mosca MQTT\\node_modules\\mosca\\lib\\client.j
s:491:9)\n    at Connection.<anonymous> (C:\\Velocity\\Installed\\Mosca MQTT\\no
de_modules\\mosca\\lib\\client.js:101:12)\n    at emitOne (events.js:96:13)\n
 at Connection.emit (events.js:188:7)","client":"2546844d-f67d-46cc-9fa6-3ab02f1
03747","v":1}`

I'm having some issues about client disconnecting and reconnecting frequently. what does the invalid qos vector means? is one of the client using an invalid qos ?

**Comment by marqueeeeeee** [comment]
found the error in the client. it's subscribing to a null topic.
