### ISSUE TITLE
Installation dependencies / requirements?

### ISSUE THREAD

**Issue by Domvel** [mcollina/mosca#726]
I can't install mosca on windows 10 or linux (raspbian). 
What are the requirements for a successful installation?

First Error:
```
kerberos@0.0.23 install /home/pi/projects/mqtt/node_modules/mosca/node_modules/ascoltatori/node
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/home/pi/projects/mqtt/node_modules/mosca/node_modules/ascoltatori/node
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>

compilation terminated.
kerberos.target.mk:98: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/home/pi/projects/mqtt/node_modules/mosca/node_modules/ascoltatori/node_modules/kerberos/build'
gyp ERR! build error
 stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.9.59-v7+
 ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/projects/mqtt/node_modules/mosca/node_modules/ascoltatori/node_modules/kerberos
gyp ERR! node -v v4.8.2
 v3.4.0! node-gyp -v/
gyp ERR! not ok
```

`npm install mosca --save`

**Comment by Domvel** [comment]
For all users with same problem: try [aedes](https://github.com/mcollina/aedes). It's an alternative. In short: A working mqtt broker. Installation without issues and easy setup with node js.

**Comment by mcollina** [comment]
More or less yes. I plan to move this to aedes as soon as possible.
